import { NextResponse } from 'next/server';

// Daily Intelligence Digest — sent via Resend or any SMTP-compatible service
// Currently uses: https://resend.com (free tier: 3000 emails/month)
// Add RESEND_API_KEY to .env.local

export async function POST(req: Request) {
    const resendKey = process.env.RESEND_API_KEY;

    if (!resendKey) {
        return NextResponse.json({
            error: 'RESEND_API_KEY not configured. Get a free key at https://resend.com'
        }, { status: 503 });
    }

    const { email, summary } = await req.json();
    // summary: { marketHighlights, intelAlerts, whaleMovements, aiInsight }

    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { background: #000; color: #e8decf; font-family: 'Courier New', monospace; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 0 auto; padding: 32px 24px; }
    .header { border-bottom: 1px solid rgba(212,175,55,0.3); padding-bottom: 16px; margin-bottom: 24px; }
    .logo { font-size: 12px; letter-spacing: 0.4em; color: #d4af6e; text-transform: uppercase; font-weight: 900; }
    h1 { color: #d4af6e; font-size: 24px; margin: 8px 0; letter-spacing: -0.02em; }
    .date { font-size: 10px; color: rgba(232,222,204,0.4); letter-spacing: 0.2em; }
    .section { background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.04); border-radius: 8px; padding: 16px; margin-bottom: 16px; }
    .section-title { font-size: 9px; font-weight: 900; letter-spacing: 0.4em; text-transform: uppercase; color: #00f0ff; margin-bottom: 8px; }
    .item { font-size: 13px; color: rgba(232,222,204,0.8); line-height: 1.6; padding: 6px 0; border-bottom: 1px solid rgba(255,255,255,0.03); }
    .item:last-child { border-bottom: none; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 9px; font-weight: 900; letter-spacing: 0.1em; }
    .badge-bull { background: rgba(0,240,200,0.15); color: #00f0c8; border: 1px solid rgba(0,240,200,0.2); }
    .badge-bear { background: rgba(255,60,60,0.15); color: #ff6060; border: 1px solid rgba(255,60,60,0.2); }
    .footer { margin-top: 32px; font-size: 9px; color: rgba(232,222,204,0.2); letter-spacing: 0.1em; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">THE_SOVEREIGN_Ω</div>
      <h1>Daily Intelligence Digest</h1>
      <div class="date">${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} // CLASSIFIED</div>
    </div>

    ${summary?.marketHighlights ? `
    <div class="section">
      <div class="section-title">Market Intelligence</div>
      ${summary.marketHighlights.map((h: string) => `<div class="item">${h}</div>`).join('')}
    </div>` : ''}

    ${summary?.intelAlerts ? `
    <div class="section">
      <div class="section-title">Geopolitical Signals</div>
      ${summary.intelAlerts.map((a: string) => `<div class="item">${a}</div>`).join('')}
    </div>` : ''}

    ${summary?.whaleMovements ? `
    <div class="section">
      <div class="section-title">Whale Radar — Apex Movements</div>
      ${summary.whaleMovements.map((w: string) => `<div class="item">${w}</div>`).join('')}
    </div>` : ''}

    ${summary?.aiInsight ? `
    <div class="section">
      <div class="section-title">Neural Oracle — Daily Assessment</div>
      <div class="item">${summary.aiInsight}</div>
    </div>` : ''}

    <div class="footer">
      SOVEREIGN_OS // CLASSIFIED_LEVEL_4 // © ${new Date().getFullYear()}<br/>
      AUTO-GENERATED BY NEURAL_INTELLIGENCE_ENGINE
    </div>
  </div>
</body>
</html>`;

    try {
        const res = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${resendKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                from: 'Sovereign OS <intel@yourdomain.com>',
                to: [email],
                subject: `[SOVEREIGN] Daily Intelligence Brief — ${new Date().toLocaleDateString('en-US')}`,
                html: htmlBody,
            }),
        });

        if (!res.ok) {
            const err = await res.text();
            return NextResponse.json({ error: err }, { status: res.status });
        }

        return NextResponse.json({ success: true, message: 'Intelligence report dispatched.' });
    } catch (err: any) {
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
